### ISSUE TITLE
Difference with flutter_tts? 

### ISSUE THREAD

**Issue by flutter-painter** [Mobile-Artificial-Intelligence/babylon_tts#2]
Hi,
I really like your approach but why build such tool when flutter_tts is available and works offline?

**Comment by danemadsen** [comment]
Because flutter_tts doesn't work with Linux and it doesn't use neural text to speech and instead uses the different TTS apis available for each platform (atleast that's how I think it works). babylon_tts is standalone and works on all platforms.

**Comment by flutter-painter** [comment]
Thank you for your explanation, is there any limits to the available languages ? 
I guess this depends on deep-phonemizer and VITS support but fail to see the actual limits

**Comment by danemadsen** [comment]
There isn't any limit to either (I'm aware of) but you might have trouble finding models compatible.

**Comment by flutter-painter** [comment]
ok sounds very good, is there any resource where you could point me/us for finding such models ?
